### ISSUE TITLE
java.lang.NullPointerException

### ISSUE THREAD

**Issue by jacobrosenthal** [jacobrosenthal/arduino-cli#9]
Looks like something changed with arduino binaries somewhere before 1.6.12

If it cant find the serial port you set on the command line, even if you're just verifying and not uploading, it java.lang.NullPointerException

```
java.lang.NullPointerException
  at processing.app.BaseNoGui.selectSerialPort(BaseNoGui.java:1088)
  at processing.app.helpers.CommandlineParser.parseArgumentsPhase1(CommandlineParser.java:143)
  at processing.app.Base.<init>(Base.java:273)
  at processing.app.Base.guardedMain(Base.java:219)
  at processing.app.Base.main(Base.java:132)
[Finished in 4.0s with exit code 255]
[cmd: ['/Applications/Arduino.app/Contents/MacOS/Arduino', '--board', 'arduino:avr:uno', '--port', '/dev/tty.usbmodem1411', '--verify', '/Users/jacobrosenthal/Desktop/NullStreamExample/NullStreamExample.ino']]
[dir: /Users/jacobrosenthal/Desktop/NullStreamExample]
[path: /usr/bin:/bin:/usr/sbin:/sbin]
```

To fix remove or fix the serialport in your user settings. Also I think well patch so that port isnt set for 'just build'

**Comment by kesarrani** [comment]
java.lang.NullPointerException how to slove plz help me
